import jwt from "jsonwebtoken";

export const validateUserToken = async (req, res, next) => {
  const token = req.cookies.bmstoken;

  if (!token) {
    return res
      .status(401)
      .send({ success: false, message: "Invalid Credentials, Please Login." });
  }
  try {
    const verifiedUser = jwt.verify(token, process.env.secretKey); // the key verifies the token was indeed generated by this server
    req.userId = verifiedUser.userId;
    next();
  } catch (error) {
    res.status(401).send({
      success: false,
      message: "Invalid or expired token",
    });
  }
};
